image: python:latest

before_script:
  - apt-get -qq update && apt-get install -y python3 python3-virtualenv python3-pip
  - virtualenv venv
  - . venv/bin/activate
  - python3 -V
  - pip install pandas

stages:
  - test

pytest:
  stage: test
  script:
    - pip install --upgrade pip
    - pip install numpy matplotlib sklearn joblib
    - python test_prediction.py
