version: "3.8"

services:
  apache:
    build: ./apache/
    container_name: apache
    ports:
      - "8080:80"
    depends_on:
      - mongodb
      - elasticsearch
    networks:
      - app

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=projet_nosql
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
      - MONGODB_DATA_DIR=/data/db
      - MONDODB_LOG_DIR=/dev/null
    volumes:
      - ./mongodb/data/:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - app

  elasticsearch:
    container_name: esdb
    image: elasticsearch:7.8.1
    environment:
      - node.name=projet-nosql-es
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - app

volumes:
  mongodb/data:
    driver: local
  es-data:
    driver: local

networks:
  app:
    driver: bridge
